---
title: "Project2"
author: "Yuli Yin"
date: "10/7/2022"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
packages.used=c("shiny","tidyverse","dplyr","ggplot2")

# check packages that need to be installed.
packages.needed=setdiff(packages.used, 
                        intersect(installed.packages()[,1], 
                        packages.used))

# install additional packages
if(length(packages.needed)>0){
  install.packages(packages.needed, dependencies = TRUE)
}

# load packages
library(shiny)
library(tidyverse)
library(dplyr)
library(ggplot2)
```

```{r}
# Import the datasets 
electric <- read.csv('../data/Electric_Consumption_And_Cost__2010_-_Feb_2022_.csv')
water <- read.csv('../data/Water_Consumption_And_Cost__2013_-_Feb_2022_.csv')
gas <- read.csv('../data/Heating_Gas_Consumption_And_Cost__2010_-__Feb_2022_.csv')

# Select data from 2019-2022
electric2 <- electric
water2 <- water
gas2 <- gas
```

```{r}
# Select data from 2019-2022
electric2$Revenue.Year <- as.integer(substr(electric2$Revenue.Month,1,4))
water2$Revenue.Year <- as.integer(substr(water2$Revenue.Month,1,4))
gas2$Revenue.Year <- as.integer(substr(gas2$Revenue.Month,1,4))

electric2 <- electric2[electric2$Revenue.Year>=2019,]
water2 <- water2[water2$Revenue.Year>=2019,]
gas2 <- gas2[gas2$Revenue.Year>=2019,]
```

```{r}
# Select key columns from original datasets
electric2 <- electric2[,c('Borough','Revenue.Month','Consumption..KWH.')]
water2 <- water2[,c('Borough','Revenue.Month','Consumption..HCF.')]
gas2 <- gas2[,c('Borough','Revenue.Month','Consumption..Therms.')]
```

```{r}
# Sort data
electric2 <- electric2[order(electric2$Borough,electric2$Revenue.Month),]
water2 <- water2[order(water2$Borough,water2$Revenue.Month),]
gas2 <- gas2[order(gas2$Borough,gas2$Revenue.Month),]
```

```{r}
# Group by Borough and date, take average 
electric_groupby <- electric2 %>% 
                      group_by(Borough,Revenue.Month) %>% 
                      summarise(mean=sum(Consumption..KWH.))

water_groupby <- water2 %>% 
                  group_by(Borough,Revenue.Month) %>% 
                  summarise(mean = sum(Consumption..HCF.))

gas_groupby <- gas2 %>% 
                group_by(Borough,Revenue.Month) %>% 
                summarise(mean = sum(Consumption..Therms.))
```

```{r}
# Merge three energy
electric_groupby$Energy <-  'Electric'
water_groupby$Energy <- 'Water'
gas_groupby$Energy <- 'Heating.Gas'
gas_groupby <- gas_groupby[gas_groupby$Revenue.Month!='2022-04',]
energy <- rbind(electric_groupby,water_groupby,gas_groupby)
colnames(energy)[3] <- 'Sum.Consumption'
```

```{r}
# Plots: trend over the years
# Select by borough name, energy type
# Test 1: Borough = BRONX, Energy = Water
test_data1 <- energy %>% filter((Borough == "BRONX")&(Energy == 'Water'))
ggplot(data=test_data1, aes(x=Revenue.Month, y=Sum.Consumption, group=1)) +
  geom_line(color = "#0099f9", size = 0.5)+
  #geom_point(color = "#0099f9", size = 1) +
  xlab("Date") + 
  ylab("Sum Consumption") +
  theme(axis.text.x = element_text(angle = 45, vjust = 1, hjust = 1)) +
  scale_x_discrete(guide = guide_axis(check.overlap = TRUE))
```
```{r}
# Test 2: Borough = BRONX, Energy = All
test_data2 <- energy %>% filter(Borough == "BRONX")
scale_electric <- test_data2 %>% filter(Energy == 'Electric')
scale_water <- test_data2 %>% filter(Energy == 'Water')
scale <- mean(scale_electric$Sum.Consumption)/mean(scale_water$Sum.Consumption)

test_plot2 <- ggplot(data = test_data2[(test_data2$Energy == 'Electric') | 
                                       (test_data2$Energy == 'Heating.Gas'),],
                     aes(x=Revenue.Month, y=Sum.Consumption, group =Energy)) +
              geom_line(aes(color = Energy)) +
              geom_line(data = test_data2[test_data2$Energy == 'Water',],
                        aes(x=Revenue.Month, y=Sum.Consumption*scale, group=1, color = Energy)) +
              scale_y_continuous(name = 'Sum Consumption (Electric, Heating Gas)',
                                 sec.axis = sec_axis(trans=~.*(1/scale),name='Sum Consumption (Water)')) +
              xlab("Date") + 
              ylab("Sum Consumption") +
              theme(axis.text.x = element_text(angle = 45, vjust = 1, hjust = 1)) +
              scale_x_discrete(guide = guide_axis(check.overlap = TRUE)) +
              theme(legend.position = "bottom")

test_plot2
```
```{r}
# Test 3: Borough = All, Energy = Water
test_data3 <- energy %>% 
                filter(Energy == 'Heating.Gas') %>%
                group_by(Revenue.Month) %>% 
                summarise(mean=sum(Sum.Consumption))
colnames(test_data3)[2] <- 'Sum.Consumption'

ggplot(data=test_data3, aes(x=Revenue.Month, y=Sum.Consumption, group=1)) +
  geom_line(color = "#0099f9", size = 0.5)+
  #geom_point(color = "#0099f9", size = 1) +
  xlab("Date") + 
  ylab("Sum Consumption") +
  theme(axis.text.x = element_text(angle = 45, vjust = 1, hjust = 1)) +
  scale_x_discrete(guide = guide_axis(check.overlap = TRUE))
```

```{r}
# Test 4: Borough = All, Energy = All
test_data4 <- energy %>% 
                group_by(Revenue.Month, Energy) %>% 
                summarise(mean=sum(Sum.Consumption))
colnames(test_data4)[3] <- 'Sum.Consumption'

scale_electric4 <- test_data4 %>% filter(Energy == 'Electric')
scale_water4 <- test_data4 %>% filter(Energy == 'Water')
scale4 <- mean(scale_electric4$Sum.Consumption)/mean(scale_water4$Sum.Consumption)

test_plot4 <- ggplot(data = test_data4[(test_data4$Energy == 'Electric') | 
                                       (test_data4$Energy == 'Heating.Gas'),],
                     aes(x=Revenue.Month, y=Sum.Consumption, group =Energy)) +
              geom_line(aes(color = Energy)) +
              geom_line(data = test_data4[test_data4$Energy == 'Water',],
                        aes(x=Revenue.Month, y=Sum.Consumption*scale4, group=1, color = Energy)) +
              scale_y_continuous(name = 'Sum Consumption (Electric, Heating Gas)',
                                 sec.axis = sec_axis(trans=~.*(1/scale4),name='Sum Consumption (Water)')) +
              xlab("Date") + 
              ylab("Sum Consumption") +
              theme(axis.text.x = element_text(angle = 45, vjust = 1, hjust = 1)) +
              scale_x_discrete(guide = guide_axis(check.overlap = TRUE)) +
              theme(legend.position = "bottom")

test_plot4
```

```{r}
# Define UI ----
ui <- fluidPage(
  # App title ----
  titlePanel("Energy Consumption Trend over the Years"),
  # Sidebar layout with input and output definitions ----
  sidebarLayout(
    # Sidebar panel for inputs ----
    sidebarPanel(
      # Input: Select for the borough ----
      selectInput(inputId = "Borough",
                  label = "Choose a borough:",
                  choices = c("Manhattan", "Bronx", "Brooklyn", "Queens", 
                              "Staten Island", "FHA", "Non Development Facility", "All")),
      
      # Input: Select for the enegry type ----
      selectInput(inputId = "Energy",
                  label = "Choose an energy type:",
                  choices = c("Water", "Electric", "Heating Gas", "All"))
    ),
    # Main panel for displaying output ----
    mainPanel(
      # Output: trend of consumption over the years ----
      plotOutput(outputId = "tsPlot")
    )
  )
)
```

```{r}
# Define server ----
server <- function(input, output) {

  energy_data <- reactive({
    # Energy = water
    if ("Manhattan" %in% input$Borough & "Water" %in% input$Energy) {
      return(energy %>% filter(Borough == "MANHATTAN" & Energy == 'Water'))
    }
    if ("Bronx" %in% input$Borough & "Water" %in% input$Energy) {
      return(energy %>% filter(Borough == "BRONX" & Energy == 'Water'))
    }
    if ("Brooklyn" %in% input$Borough & "Water" %in% input$Energy) {
      return(energy %>% filter(Borough == "BROOKLYN" & Energy == 'Water'))
    }
    if ("Queens" %in% input$Borough & "Water" %in% input$Energy) {
      return(energy %>% filter(Borough == "QUEENS" & Energy == 'Water'))
    }
    if ("Staten Island" %in% input$Borough & "Water" %in% input$Energy) {
      return(energy %>% filter(Borough == "STATEN ISLAND" & Energy == 'Water'))
    }
    if ("FHA" %in% input$Borough & "Water" %in% input$Energy) {
      return(energy %>% filter(Borough == "FHA" & Energy == 'Water'))
    }
    if ("Non Development Facility" %in% input$Borough & "Water" %in% input$Energy) {
      return(energy %>% filter(Borough == "NON DEVELOPMENT FACILITY" & Energy == 'Water'))
    }
    if ("All" %in% input$Borough & "Water" %in% input$Energy) {
      data <- energy %>% filter(Energy == 'Water') %>% group_by(Revenue.Month) %>% 
        summarise(mean=sum(Sum.Consumption))
      colnames(data)[2] <- 'Sum.Consumption'
      return(data)
    }
    # Energy = Electric
    if ("Manhattan" %in% input$Borough & "Electric" %in% input$Energy) {
      return(energy %>% filter(Borough == "MANHATTAN" & Energy == 'Electric'))
    }
    if ("Bronx" %in% input$Borough & "Electric" %in% input$Energy) {
      return(energy %>% filter(Borough == "BRONX" & Energy == 'Electric'))
    }
    if ("Brooklyn" %in% input$Borough & "Electric" %in% input$Energy) {
      return(energy %>% filter(Borough == "BROOKLYN" & Energy == 'Electric'))
    }
    if ("Queens" %in% input$Borough & "Electric" %in% input$Energy) {
      return(energy %>% filter(Borough == "QUEENS" & Energy == 'Electric'))
    }
    if ("Staten Island" %in% input$Borough & "Electric" %in% input$Energy) {
      return(energy %>% filter(Borough == "STATEN ISLAND" & Energy == 'Electric'))
    }
    if ("FHA" %in% input$Borough & "Electric" %in% input$Energy) {
      return(energy %>% filter(Borough == "FHA" & Energy == 'Electric'))
    }
    if ("Non Development Facility" %in% input$Borough & "Electric" %in% input$Energy) {
      return(energy %>% filter(Borough == "NON DEVELOPMENT FACILITY" & Energy == 'Electric'))
    }
    if ("All" %in% input$Borough & "Electric" %in% input$Energy) {
      data <- energy %>% filter(Energy == 'Electric') %>% group_by(Revenue.Month) %>% 
        summarise(mean=sum(Sum.Consumption))
      colnames(data)[2] <- 'Sum.Consumption'
      return(data)
    }
    # Energy = Heating Gas
    if ("Manhattan" %in% input$Borough & "Heating Gas" %in% input$Energy) {
      return(energy %>% filter(Borough == "MANHATTAN" & Energy == 'Heating.Gas'))
    }
    if ("Bronx" %in% input$Borough & "Heating Gas" %in% input$Energy) {
      return(energy %>% filter(Borough == "BRONX" & Energy == 'Heating.Gas'))
    }
    if ("Brooklyn" %in% input$Borough & "Heating Gas" %in% input$Energy) {
      return(energy %>% filter(Borough == "BROOKLYN" & Energy == 'Heating.Gas'))
    }
    if ("Queens" %in% input$Borough & "Heating Gas" %in% input$Energy) {
      return(energy %>% filter(Borough == "QUEENS" & Energy == 'Heating.Gas'))
    }
    if ("Staten Island" %in% input$Borough & "Heating Gas" %in% input$Energy) {
      return(energy %>% filter(Borough == "STATEN ISLAND" & Energy == 'Heating.Gas'))
    }
    if ("FHA" %in% input$Borough & "Heating Gas" %in% input$Energy) {
      return(energy %>% filter(Borough == "FHA" & Energy == 'Heating.Gas'))
    }
    if ("Non Development Facility" %in% input$Borough & "Heating Gas" %in% input$Energy) {
      return(energy %>% filter(Borough == "NON DEVELOPMENT FACILITY" & Energy == 'Heating.Gas'))
    }
    if ("All" %in% input$Borough & "Heating Gas" %in% input$Energy) {
      data <- energy %>% filter(Energy == 'Heating.Gas') %>% group_by(Revenue.Month) %>% 
        summarise(mean=sum(Sum.Consumption))
      colnames(data)[2] <- 'Sum.Consumption'
      return(data)
    }    
    # Energy = All
    if ("Manhattan" %in% input$Borough & "All" %in% input$Energy) {
      return(energy %>% filter(Borough == "MANHATTAN"))
    }
    if ("Bronx" %in% input$Borough & "All" %in% input$Energy) {
      return(energy %>% filter(Borough == "BRONX"))
    }
    if ("Brooklyn" %in% input$Borough & "All" %in% input$Energy) {
      return(energy %>% filter(Borough == "BROOKLYN"))
    }
    if ("Queens" %in% input$Borough & "All" %in% input$Energy) {
      return(energy %>% filter(Borough == "QUEENS"))
    }
    if ("Staten Island" %in% input$Borough & "All" %in% input$Energy) {
      return(energy %>% filter(Borough == "STATEN ISLAND"))
    }
    if ("FHA" %in% input$Borough & "All" %in% input$Energy) {
      return(energy %>% filter(Borough == "FHA"))
    }
    if ("Non Development Facility" %in% input$Borough & "All" %in% input$Energy) {
      return(energy %>% filter(Borough == "NON DEVELOPMENT FACILITY"))
    }
    if ("All" %in% input$Borough & "All" %in% input$Energy) {
      data <- energy %>% group_by(Revenue.Month, Energy) %>% 
        summarise(mean=sum(Sum.Consumption))
      colnames(data)[3] <- 'Sum.Consumption'
      return(data)
    }     
  })

  output$tsPlot <-renderPlot({
    dat = energy_data()
    if (input$Energy != 'All') {
      p <- ggplot(data=dat, aes(x=Revenue.Month, y=Sum.Consumption, group=1)) +
            geom_line(color = "#0099f9", size = 0.5)+
            xlab("Date") + 
            ylab("Sum Consumption") +
            theme(axis.text.x = element_text(angle = 45, vjust = 1, hjust = 1)) +
            scale_x_discrete(guide = guide_axis(check.overlap = TRUE))
    }
    if (input$Energy == 'All') {
      scale_electric <- dat %>% filter(Energy == 'Electric')
      scale_water <- dat %>% filter(Energy == 'Water')
      scale <- mean(scale_electric$Sum.Consumption)/mean(scale_water$Sum.Consumption)
      
      p <- ggplot(data=dat[(dat$Energy=='Electric')|(dat$Energy=='Heating.Gas'),],
             aes(x=Revenue.Month, y=Sum.Consumption, group=Energy)) +
            geom_line(aes(color = Energy)) +
            geom_line(data=dat[dat$Energy == 'Water',],
                      aes(x=Revenue.Month, y=Sum.Consumption*scale, group=1, color = Energy)) +
            scale_y_continuous(name = 'Sum Consumption (Electric, Heating Gas)',
                               sec.axis = sec_axis(trans=~.*(1/scale),name='Sum Consumption (Water)')) +
            xlab("Date") + 
            theme(axis.text.x = element_text(angle = 45, vjust = 1, hjust = 1)) +
            scale_x_discrete(guide = guide_axis(check.overlap = TRUE)) +
            theme(legend.position = "bottom")
    }
    p
  })
}

shinyApp(ui, server)
```

